#!/bin/bash

if [ -e `dirname $0`/env/bin/activate ]; then
    source `dirname $0`/env/bin/activate
fi

if [ -e `dirname $0`/env/hdf5/lib ]; then
    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:`dirname "$0"`/env/hdf5/lib
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname "$0"`/env/hdf5/lib
fi

REAL=`python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "$0"`
DIR=`dirname "$REAL"`
$DIR/xsqutils/xsq.py "$@"
