#!/bin/bash
source `dirname $0`/env/bin/activate
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:`dirname "$0"`/env/hdf5/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname "$0"`/env/hdf5/lib
xsqutils/xsq.py "$@"
